//! Single-screen CLI overview, generated by walking clap's `Command` metadata
//! so it can never drift from the actual argument definitions.

use clap::builder::PossibleValue;
use clap::{Arg, ArgAction, Command};

/// Render the whole CLI surface as one compact reference screen.
///
/// Unlike clap's default top-level help (which only lists command names and
/// forces a `keytap <cmd> --help` round-trip to discover the optional name arg
/// and format flags), this shows every command inline with its arguments,
/// then a short legend explaining the shared options and their choices.
pub fn overview(cli: &Command) -> String {
    let mut out = String::new();

    if let Some(about) = cli.get_about() {
        out.push_str(&about.to_string());
        out.push_str("\n\n");
    }

    let bin = cli.get_name();
    out.push_str(&format!("Usage: {bin} <COMMAND> [ARGS]\n\nCommands\n"));

    // First pass: build each command's usage string and remember the widest
    // one so the descriptions line up in a single column.
    let commands: Vec<(&Command, String, String)> = cli
        .get_subcommands()
        .filter(|c| c.get_name() != "help")
        .map(|c| {
            let usage = command_usage(c);
            let about = c
                .get_about()
                .map(|a| a.to_string())
                .unwrap_or_default();
            (c, usage, about)
        })
        .collect();

    let width = commands.iter().map(|(_, u, _)| u.len()).max().unwrap_or(0);

    for (_, usage, about) in &commands {
        out.push_str(&format!("  {usage:width$}  {about}\n"));
    }

    // Second pass: collect the shared arguments once and describe them as a
    // legend, folding in the concrete choices from each ValueEnum.
    let legend = build_legend(&commands);
    if !legend.is_empty() {
        out.push('\n');
        out.push_str(&legend);
    }

    let options: Vec<(String, String)> = cli
        .get_arguments()
        .filter(|arg| in_overview(arg))
        .map(|arg| {
            let description = arg.get_help().map(|help| help.to_string()).unwrap_or_default();
            (legend_key(arg), description)
        })
        .collect();
    if !options.is_empty() {
        let width = options.iter().map(|(key, _)| key.len()).max().unwrap_or(0);
        out.push_str("\nOptions\n");
        for (key, description) in options {
            out.push_str(&format!("  {key:width$}  {description}\n"));
        }
    }

    out.push_str("\nSkip repeated prompts for a key: `keytap remember NAME` (see `keytap remember --help`).\nHolds that expire instead (ssh-agent, TTLs): see `keytap reveal --help`.\nCI (headless, $CI set): keys come from `$KEYTAP_KEY_<NAME>` \u{2014} see `keytap reveal --help`.\n");

    out.push_str("Run `");
    out.push_str(bin);
    out.push_str(" <COMMAND> --help` for the full details of any command.\n");
    out
}

/// Reuse-without-re-auth guidance, shown by `keytap reveal --help`. By default
/// keytap derives on demand and stores nothing; `keytap remember` is the
/// built-in opt-in hold (no TTL; OS keychain or a plain file, see REMEMBER).
/// The agent/variable patterns remain the recommended *bounded* holds — they
/// expire, remembered keys don't — so they are presented as deliberate
/// alternatives, not leftovers.
pub(crate) const REUSE: &str = "Reusing a key without re-authenticating each time\n  By default keytap derives on demand and stores nothing. The built-in way to\n  stop repeated prompts is to remember the key on this machine (no expiry \u{2014}\n  see `keytap remember --help` for where it lands and the exact trade-off):\n\n    keytap remember deploy    # one ceremony; 'deploy' stops prompting on this machine\n    keytap forget deploy      # back to prompting (or `keytap forget --all`)\n\n  Prefer a hold that expires on its own? Hand the key to a standard holder:\n\n  SSH (many connections, one prompt, self-expiring):\n    eval \"$(ssh-agent -s)\"\n    keytap reveal ha --as ssh | ssh-add -t 900 -    # 15-min hold, then gone\n\n  A secret reused within one script (bounded to the process):\n    KEY=$(keytap reveal deploy --as hex); use \"$KEY\"; unset KEY\n\n  A secret another tool reads from the OS keychain: remember it, then let the\n  tool call keytap \u{2014} `keytap reveal deploy` no longer prompts once remembered.\n\n  CI and other headless jobs ($CI set): keytap never prompts there (--prompt\n  overrides); it reads the derived key from $KEYTAP_KEY_<NAME> instead \u{2014} the\n  key name uppercased, everything outside A-Z0-9 flattened to _ (my-app ->\n  KEYTAP_KEY_MY_APP). The value is exactly the age encoding below \u{2014} its\n  checksum makes a mangled secret fail loudly instead of deriving a different\n  key. A set variable beats remembered keys and ceremonies. If it leaks, that\n  name is burned: derivation is deterministic, so retire the name.\n    keytap reveal ci --as age | gh secret set KEYTAP_KEY_CI   # once, locally\n    # job env: KEYTAP_KEY_CI=<that secret>, then `keytap decrypt ci` just works\n\n  Whatever holds the key\u{2014}keychain entry, agent, variable\u{2014}must be trusted accordingly.";

/// The remembered-keys contract, shown by `keytap remember --help`. States
/// plainly what is stored, where, for how long, and what the trade-off is, so
/// the one command that breaks keytap's statelessness is also the one place
/// that documents it.
pub(crate) const REMEMBER: &str = "What remembering means\n  `keytap remember NAME` runs one passkey ceremony, then stores the derived raw\n  key on this machine. From then on, keytap commands for NAME use the stored\n  key without prompting. Nothing is ever stored unless you opt in: run\n  `remember`, or choose \u{2018}remember this key\u{2019} on the phone page after a QR-code\n  approval \u{2014} one more passkey check there confirms it, then it stores the\n  same way. Key material is not printed.\n\n  Where the key lives\n    A plain file: ~/.local/state/keytap/remembered.json (0600, honors\n    $XDG_STATE_HOME), NOT encrypted at rest. On machines with an OS keychain\n    (macOS Keychain; Secret Service on desktop Linux), remember upgrades to it\n    automatically: service `keytap`, account `remember:<root>:<name>`,\n    encrypted at rest by the keychain. The success message says which one was\n    used; lookups check the keychain first, then the file.\n\n  Scope & lifetime\n    - No TTL: the key stays until `keytap forget NAME`, `keytap forget --all`,\n      or you replace the passkey (`keytap init` wipes all remembered keys).\n    - Machine-local: remembering here does not affect your other machines.\n    - Passkey-bound: keys remembered under a replaced passkey are never used.\n\n  Security trade-off\n    Any process running as your user may be able to invoke keytap and use a\n    remembered key without a ceremony. In the plain file (no OS keychain),\n    anyone who can read your files (root, backups, disk images) can also use\n    the key: treat it like an unencrypted SSH private key. When you want a\n    hold that expires instead, use an agent:\n    `keytap reveal ha --as ssh | ssh-add -t 900 -` (see `keytap reveal --help`).";

/// Arguments intentionally kept out of the at-a-glance overview (still shown by
/// each subcommand's own `--help`). Niche switches that would only add noise;
/// `--force` is taught by init's refusal message at exactly the moment it
/// applies.
const OVERVIEW_SKIP: &[&str] = &["no_self", "force"];

/// Whether this argument should appear in the generated overview.
fn in_overview(arg: &Arg) -> bool {
    !arg.is_hide_set() && !is_builtin(arg) && !OVERVIEW_SKIP.contains(&arg.get_id().as_str())
}

/// A command's inline signature, e.g. `reveal [NAME] [--as VAL]`.
fn command_usage(cmd: &Command) -> String {
    let mut parts = vec![cmd.get_name().to_string()];

    for arg in cmd.get_arguments() {
        if !in_overview(arg) {
            continue;
        }
        parts.push(token(arg));
    }

    parts.join(" ")
}

/// The bracketed token for a single argument.
fn token(arg: &Arg) -> String {
    let name = arg.get_id().as_str().to_uppercase();

    if arg.is_positional() {
        // Required positionals stay bare (FILE); optional ones get brackets.
        if arg.is_required_set() {
            name
        } else {
            format!("[{name}]")
        }
    } else {
        // A long flag; show `--flag` for switches, `--flag VAL` when it takes a value.
        let flag = flag_name(arg);
        if takes_value(arg) {
            format!("[{flag} VAL]")
        } else {
            format!("[{flag}]")
        }
    }
}

/// Build the legend describing each distinct optional argument once. When the
/// same argument appears on several commands (e.g. `--as` on both `public`
/// and `reveal`), its accepted values are merged into the union so the overview
/// never understates the choices a command actually supports.
fn build_legend(commands: &[(&Command, String, String)]) -> String {
    // Preserve first-seen order while accumulating across commands.
    let mut order: Vec<String> = Vec::new();
    let mut help: std::collections::HashMap<String, String> = Default::default();
    let mut choices: std::collections::HashMap<String, Vec<String>> = Default::default();
    let mut default: std::collections::HashMap<String, Option<String>> = Default::default();

    for (cmd, _, _) in commands {
        for arg in cmd.get_arguments() {
            if !in_overview(arg) {
                continue;
            }

            let key = legend_key(arg);
            if !order.contains(&key) {
                order.push(key.clone());
                help.insert(key.clone(), arg.get_help().map(|h| h.to_string()).unwrap_or_default());
                default.insert(key.clone(), default_value(arg));
            }

            // Union the accepted values across every command sharing this key.
            let bucket = choices.entry(key).or_default();
            for value in possible_values(arg) {
                if !bucket.contains(&value) {
                    bucket.push(value);
                }
            }
        }
    }

    if order.is_empty() {
        return String::new();
    }

    let lines: Vec<(String, String)> = order
        .into_iter()
        .map(|key| {
            // Fold in concrete choices and the default so the reader never has
            // to open a subcommand's help to learn the accepted values.
            let mut desc = help.remove(&key).unwrap_or_default();
            let values = choices.remove(&key).unwrap_or_default();
            if !values.is_empty() {
                desc.push_str(&format!("  ({})", values.join(" | ")));
            }
            if let Some(Some(d)) = default.remove(&key) {
                desc.push_str(&format!("  [default: {d}]"));
            }
            (key, desc)
        })
        .collect();

    let width = lines.iter().map(|(k, _)| k.len()).max().unwrap_or(0);
    let mut out = String::from("Arguments & options\n");
    for (key, desc) in lines {
        out.push_str(&format!("  {key:width$}  {desc}\n"));
    }
    out
}

/// The left-hand column label for an argument in the legend.
fn legend_key(arg: &Arg) -> String {
    if arg.is_positional() {
        arg.get_id().as_str().to_uppercase()
    } else {
        let mut key = flag_name(arg);
        if takes_value(arg) {
            key.push_str(" VAL");
        }
        key
    }
}

/// `--long` (falling back to `-x`) for a flag argument.
fn flag_name(arg: &Arg) -> String {
    if let Some(long) = arg.get_long() {
        format!("--{long}")
    } else if let Some(short) = arg.get_short() {
        format!("-{short}")
    } else {
        arg.get_id().as_str().to_string()
    }
}

/// The ValueEnum choices for an argument, if it constrains its input. Boolean
/// switches don't take a value, so their implicit `true`/`false` isn't listed.
fn possible_values(arg: &Arg) -> Vec<String> {
    if !takes_value(arg) {
        return Vec::new();
    }
    arg.get_possible_values()
        .iter()
        .filter(|pv| !pv.is_hide_set())
        .map(PossibleValue::get_name)
        .map(str::to_string)
        .collect()
}

fn default_value(arg: &Arg) -> Option<String> {
    let defaults = arg.get_default_values();
    if defaults.is_empty() {
        None
    } else {
        Some(defaults.iter().map(|s| s.to_string_lossy()).collect::<Vec<_>>().join(", "))
    }
}

/// Whether an argument consumes a value (vs. being a boolean switch).
fn takes_value(arg: &Arg) -> bool {
    !matches!(
        arg.get_action(),
        ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Help | ArgAction::Version
    )
}

/// clap injects `--help`/`--version`; keep them out of the per-command usage.
fn is_builtin(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Help | ArgAction::Version)
}
